select
  D.PSEUDO_DAWCY,
  D.GRUPA_KRWI,
  Z.PSEUDO_WAMPIRA
from ZLECENIA Z
inner join DONACJE DON on Z.NR_ZLECENIA = DON.NR_ZLECENIA
inner join DAWCY D on DON.PSEUDO_DAWCY = D.PSEUDO_DAWCY
inner join WAMPIRY W on Z.PSEUDO_WAMPIRA = W.PSEUDO_WAMPIRA
inner join JEZYKI_OBCE_W W3 on Z.PSEUDO_WAMPIRA = W3.PSEUDO_WAMPIRA where W3.JEZYK_OBCY = 'polski';