DROP TABLE Wampiry CASCADE CONSTRAINTS;
DROP TABLE Zlecenia CASCADE CONSTRAINTS;
DROP TABLE Dawcy CASCADE CONSTRAINTS;
DROP TABLE Donacje CASCADE CONSTRAINTS;
DROP TABLE Sprawnosci CASCADE CONSTRAINTS;
DROP TABLE Sprawnosci_w CASCADE CONSTRAINTS;
DROP TABLE Jezyki_obce CASCADE CONSTRAINTS;
DROP TABLE Jezyki_obce_w CASCADE CONSTRAINTS;