SELECT
  WAMPIRY.PSEUDO_WAMPIRA AS "PSEUDO WAMPIRA",
  WAMPIRY.PLEC_WAMPIRA   AS "PLEC WAMPIRA",
  WAMPIRY.PSEUDO_SZEFA   AS "PSEUDO SZEFA",
  W.PLEC_WAMPIRA         AS "PLEC SZEFA"
FROM WAMPIRY
  LEFT JOIN WAMPIRY W ON WAMPIRY.PSEUDO_SZEFA = W.PSEUDO_WAMPIRA