
CREATE VIEW zadania AS
  SELECT
    Z.NR_ZLECENIA,
    Z.PSEUDO_WAMPIRA
  FROM ZLECENIA Z INNER JOIN DONACJE D ON Z.NR_ZLECENIA = D.NR_ZLECENIA
    JOIN WAMPIRY W ON Z.PSEUDO_WAMPIRA = W.PSEUDO_WAMPIRA
    LEFT JOIN DONACJE D2 ON Z.NR_ZLECENIA = D2.NR_ZLECENIA
  WHERE W.PSEUDO_WAMPIRA != 'Drakula' AND W.PSEUDO_SZEFA != 'Drakula' and d2.NR_ZLECENIA is null;

SELECT *
FROM zadania;