ALTER SESSION SET NLS_DATE_FORMAT = 'DD.MM.YYYY';

SELECT DAWCY.PSEUDO_DAWCY
FROM DAWCY
  JOIN DONACJE D ON DAWCY.PSEUDO_DAWCY = D.PSEUDO_DAWCY
WHERE D.DATA_ODDANIA >= '20.07.2005' AND D.DATA_ODDANIA <= '20.08.2005';