CREATE OR REPLACE TRIGGER ZAD23
BEFORE INSERT
ON BANDY
FOR EACH ROW
DECLARE
  najwyzsy BANDY.nr_bandy%TYPE := 0;
BEGIN
  SELECT MAX(nr_bandy) INTO najwyzsy FROM BANDY;
  :NEW.nr_bandy := najwyzsy+1;
END;

INSERT INTO BANDY VALUES(0, 'NOWA BANDA', 'SMIETNIK', 'ZERO');
SELECT * FROM BANDY;
ROLLBACK;