SELECT
  K1.PSEUDO,
  (K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA, 0)) AS ZJADA
FROM KOCURY K1
WHERE &n > (SELECT COUNT(distinct (K2.PRZYDZIAL_MYSZY + NVL(K2.MYSZY_EXTRA, 0)))
            FROM KOCURY K2
            WHERE (K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA, 0)) < (K2.PRZYDZIAL_MYSZY + NVL(K2.MYSZY_EXTRA, 0)))
ORDER BY ZJADA DESC;



