SELECT
  PSEUDO,
  (PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA, 0)) AS ZJADA
FROM KOCURY
WHERE (PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA, 0)) IN (
  SELECT *
  FROM (
    SELECT DISTINCT (PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA, 0)) AS ZJADA
    FROM KOCURY
    ORDER BY ZJADA DESC)
  WHERE ROWNUM <= &n)
ORDER BY ZJADA DESC;