SELECT
  K1.PSEUDO,
  (K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA, 0)) AS ZJADA
FROM KOCURY K1, KOCURY K2
WHERE K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA, 0) <= K2.PRZYDZIAL_MYSZY + NVL(K2.MYSZY_EXTRA, 0)
GROUP BY K1.PSEUDO, K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA, 0)
HAVING COUNT(DISTINCT (K2.PRZYDZIAL_MYSZY + NVL(K2.MYSZY_EXTRA, 0))) <= &n
ORDER BY 2 DESC;