SELECT
  K1.IMIE,
  ' | '             "|",
  K1.FUNKCJA,
  NVL(K2.IMIE, ' ') "Szef 1",
  NVL(K3.IMIE, ' ') "Szef 2",
  NVL(K4.IMIE, ' ') "Szef 3"
FROM KOCURY K1 LEFT JOIN KOCURY K2 ON K1.SZEF = K2.PSEUDO
  LEFT JOIN KOCURY K3 ON K2.SZEF = K3.PSEUDO
  LEFT JOIN KOCURY K4 ON K3.SZEF = K4.PSEUDO
WHERE K1.FUNKCJA = 'MILUSIA' OR K1.FUNKCJA = 'KOT';